"""
Claude CLI interface — all calls via subprocess `claude -p`.
Never uses Anthropic API directly. Uses Claude Code CLI subscription.
"""
import subprocess
import json
import logging
import os
import time
from typing import Optional

log = logging.getLogger(__name__)

CLAUDE_SONNET = "claude-sonnet-4-5"
CLAUDE_OPUS = "claude-opus-4-5"


def _run_claude(prompt: str, model: str, system: Optional[str] = None, retries: int = 3) -> str:
    cmd = ["claude", "-p", prompt, "--model", model]
    if system:
        cmd += ["--system", system]

    for attempt in range(retries):
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=180,
            )
            if result.returncode == 0:
                return result.stdout.strip()
            else:
                log.warning(f"Claude CLI error (attempt {attempt+1}): {result.stderr[:300]}")
        except subprocess.TimeoutExpired:
            log.warning(f"Claude CLI timeout (attempt {attempt+1})")
        except FileNotFoundError:
            raise RuntimeError("claude CLI not found. Ensure Claude Code is installed.")

        if attempt < retries - 1:
            time.sleep(2 ** attempt)

    return ""


def intraday_signal_check(signals: list[dict], learnings_context: str = "") -> list[dict]:
    """
    Send top signals to Claude Sonnet for final validation.
    signals: list of dicts with ticker, signal, confidence, ml_reasoning, kronos_reasoning, slm_reasoning
    Returns: enriched signals with claude_reasoning and final_confidence
    """
    if not signals:
        return []

    # Limit to top 30-40 by combined confidence
    signals = sorted(signals, key=lambda x: x.get("confidence", 0), reverse=True)[:40]

    signal_block = ""
    for i, s in enumerate(signals, 1):
        signal_block += f"""
--- Signal {i}: {s['ticker']} ---
Price: ₹{s.get('price', 0):.2f}
Signal: {s.get('signal')} | Combined Confidence: {s.get('confidence', 0)*100:.1f}%
ML: {s.get('ml_reasoning', '')[:300]}
Kronos: {s.get('kronos_reasoning', '')[:300]}
SLM: {s.get('slm_reasoning', '')[:300]}
Stop Loss: ₹{s.get('stop_loss', 0):.1f} | Target: ₹{s.get('target', 0):.1f}
"""

    prompt = f"""You are reviewing intraday NSE stock signals generated by ML + Kronos + SLM models.

{f"Recent learning from past sessions:{chr(10)}{learnings_context}{chr(10)}" if learnings_context else ""}

SIGNALS TO REVIEW:
{signal_block}

For each signal, provide:
1. CONFIRM or REJECT (with brief reason, 1 sentence max per signal)
2. Adjusted confidence (0.0-1.0)
3. Any additional insight the models may have missed

Respond as JSON array:
[{{"ticker": "X", "action": "CONFIRM|REJECT", "confidence": float, "note": "brief insight"}}]

Be concise and decisive. No lengthy explanations."""

    system = """You are a senior Indian stock market analyst reviewing algorithmic signals.
You have deep knowledge of NSE market microstructure, Nifty sector dynamics, FII behavior patterns,
and Indian corporate earnings cycles. You think fast and sharp. Under 2 minutes for this batch."""

    raw = _run_claude(prompt, CLAUDE_SONNET, system=system)

    if not raw:
        log.warning("Claude returned empty response for intraday check")
        return signals

    # Parse JSON from response
    try:
        start = raw.find("[")
        end = raw.rfind("]") + 1
        if start >= 0 and end > start:
            claude_outputs = json.loads(raw[start:end])
            claude_map = {c["ticker"]: c for c in claude_outputs}

            enriched = []
            for s in signals:
                c = claude_map.get(s["ticker"], {})
                action = c.get("action", "CONFIRM")
                adj_conf = c.get("confidence", s.get("confidence", 0.5))
                note = c.get("note", "")

                s["claude_action"] = action
                s["claude_confidence"] = adj_conf
                s["claude_reasoning"] = (
                    f"Claude Sonnet ({action}):\n"
                    f"  • {note}\n"
                    f"  • Final confidence: {adj_conf*100:.1f}%"
                )
                s["final_confidence"] = adj_conf
                if action == "REJECT":
                    s["signal"] = "HOLD"
                enriched.append(s)
            return enriched
        else:
            log.warning(f"Could not parse Claude JSON. Raw: {raw[:500]}")
    except json.JSONDecodeError as e:
        log.warning(f"JSON parse error from Claude: {e}. Raw: {raw[:500]}")

    return signals


def eod_review_call(predictions: list[dict]) -> dict:
    """
    EOD Claude Opus call. Reviews all predictions vs actuals.
    Returns structured learnings.
    predictions: [{ticker, signal, predicted_close, actual_close, ml_reasoning, kronos_reasoning, slm_reasoning, claude_reasoning}]
    """
    if not predictions:
        return {"learnings": [], "summary": "No predictions today."}

    pred_block = ""
    for p in predictions:
        delta = ((p.get("actual_close", 0) - p.get("predicted_close", 0)) / p.get("predicted_close", 1)) * 100
        outcome = "✅ Correct" if (
            (p.get("signal") == "BUY" and delta > 0) or
            (p.get("signal") == "SELL" and delta < 0)
        ) else "❌ Wrong"
        pred_block += f"""
{outcome} | {p['ticker']} | Signal: {p.get('signal')}
  Predicted: ₹{p.get('predicted_close', 0):.1f} → Actual: ₹{p.get('actual_close', 0):.1f} ({delta:+.1f}%)
  ML said: {p.get('ml_reasoning', '')[:200]}
  Kronos said: {p.get('kronos_reasoning', '')[:200]}
  SLM said: {p.get('slm_reasoning', '')[:200]}
  Claude said: {p.get('claude_reasoning', '')[:200]}
"""

    prompt = f"""End-of-day model performance review for NSE trading signals.

TODAY'S PREDICTIONS VS ACTUALS:
{pred_block}

Analyze each wrong prediction deeply:
1. What did the models miss?
2. What pattern should be learned?
3. What market condition caused the failure?

Also note what worked well and why.

Provide structured learnings as JSON:
{{
  "summary": "one paragraph summary of today",
  "learnings": [
    {{
      "ticker": "X or null for general",
      "title": "short title",
      "body": "detailed learning",
      "tags": ["pattern_failure|signal_type|sector|timeframe"],
      "model_at_fault": "ml|kronos|slm|claude|all"
    }}
  ],
  "accuracy_today": {{
    "total": int,
    "correct": int,
    "pct": float
  }}
}}"""

    system = """You are a rigorous quantitative analyst doing post-market review.
You extract precise, actionable learnings from prediction errors.
Your job is to make this system smarter for tomorrow.
Be specific about what pattern failed, not generic platitudes."""

    raw = _run_claude(prompt, CLAUDE_OPUS, system=system)

    if not raw:
        return {"learnings": [], "summary": "Claude Opus review failed — no response."}

    try:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start >= 0 and end > start:
            return json.loads(raw[start:end])
    except json.JSONDecodeError as e:
        log.error(f"Failed to parse EOD review: {e}")

    return {"learnings": [], "summary": raw[:1000], "raw": raw}


def weekend_deep_review(week_learnings: list[dict], accuracy_stats: dict) -> dict:
    """
    Saturday morning — Claude Opus deep weekly analysis.
    """
    if not week_learnings:
        return {"insights": [], "recommendations": []}

    learnings_text = "\n".join(
        f"- [{l.get('learning_date')}] {l.get('title')}: {l.get('body', '')[:300]}"
        for l in week_learnings[:50]
    )

    prompt = f"""Weekly deep review of StockSense NSE trading system.

ACCURACY THIS WEEK:
{json.dumps(accuracy_stats, indent=2)}

LEARNINGS LOGGED THIS WEEK:
{learnings_text}

Provide:
1. Recurring failure patterns (what keeps going wrong?)
2. Strongest signal patterns (what's working consistently?)
3. Market regime assessment (trending/ranging/volatile?)
4. Specific model calibration recommendations
5. Sectors to watch or avoid next week

JSON response:
{{
  "regime": "trending|ranging|volatile|mixed",
  "recurring_failures": ["..."],
  "working_patterns": ["..."],
  "model_calibration": {{"lgbm": "...", "kronos": "...", "slm": "..."}},
  "next_week_focus": ["sector or pattern to prioritize"],
  "weekly_grade": "A|B|C|D"
}}"""

    raw = _run_claude(prompt, CLAUDE_OPUS)
    if not raw:
        return {"insights": [], "recommendations": []}

    try:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start >= 0 and end > start:
            return json.loads(raw[start:end])
    except Exception:
        pass

    return {"raw_review": raw}
