"""
Synthesis call builders — prompts and parsing for the final-validation layer.

The prompts and JSON parsing live here; the actual model execution is delegated to
intelligence/llm_cli.run(), which routes to whichever CLI the user connected
(Claude Code, Codex, or Gemini). All four call sites here (intraday check, EOD
review, calibration, weekend deep review) run on CLAUDE_SONNET at
config.CLAUDE_CLI_EFFORT ("low" by default) — this runs dozens of times a day
(every 30-min pipeline cycle) plus daily/weekly reviews, so token cost
compounds fast; none of these are open-ended reasoning tasks, they're bounded
JSON-in/JSON-out calls that don't need Opus-tier depth. CLAUDE_OPUS is kept
defined (unused today) in case a future call site genuinely needs deeper
reasoning. No API keys, ever — auth is via the logged-in CLI.
"""
import json
import logging
import re
from typing import Optional

from config import settings
from intelligence import llm_cli

log = logging.getLogger(__name__)

CLAUDE_SONNET = settings.CLAUDE_SONNET_MODEL
CLAUDE_OPUS = settings.CLAUDE_OPUS_MODEL


def _extract_json(raw: str, expect: str = "object"):
    """
    Robustly extract the first valid JSON object/array from a model response.
    Handles ```json fences, leading prose, and trailing commentary.
    expect: "object" -> dict, "array" -> list. Returns None on failure.
    """
    if not raw:
        return None

    # Strip markdown code fences if present
    fence = re.search(r"```(?:json)?\s*(.*?)```", raw, re.DOTALL)
    if fence:
        raw = fence.group(1)

    open_ch, close_ch = ("{", "}") if expect == "object" else ("[", "]")

    # Try direct parse first (clean responses)
    try:
        parsed = json.loads(raw.strip())
        return parsed
    except json.JSONDecodeError:
        pass

    # Bracket-matching scan to isolate the first balanced JSON span
    start = raw.find(open_ch)
    if start < 0:
        return None
    depth = 0
    in_str = False
    esc = False
    for i in range(start, len(raw)):
        ch = raw[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                candidate = raw[start : i + 1]
                try:
                    return json.loads(candidate)
                except json.JSONDecodeError as e:
                    log.warning(f"JSON candidate parse failed: {e}. Span: {candidate[:300]}")
                    return None
    return None


def _run_claude(prompt: str, model: str, system: Optional[str] = None, retries: int = 3) -> str:
    """
    Delegate to the active synthesis CLI. The `model` argument selects the tier:
    the fast model (CLAUDE_SONNET) maps to role "fast", anything else to "deep".
    Named `_run_claude` for historical reasons; the backend may be Codex or Gemini.
    """
    role = "fast" if model == CLAUDE_SONNET else "deep"
    return llm_cli.run(prompt, role=role, system=system or "", retries=retries)


def intraday_signal_check(signals: list[dict], learnings_context: str = "") -> list[dict]:
    """
    Send top signals to Claude Sonnet for final validation.
    signals: list of dicts with ticker, signal, confidence, ml_reasoning, kronos_reasoning, slm_reasoning
    Returns: enriched signals with claude_reasoning and final_confidence
    """
    if not signals:
        return []

    # Limit to top 30-40 by combined confidence
    signals = sorted(signals, key=lambda x: x.get("confidence", 0), reverse=True)[:40]

    signal_block = ""
    for i, s in enumerate(signals, 1):
        signal_block += f"""
--- Signal {i}: {s['ticker']} ---
Price: ₹{s.get('price', 0):.2f}
Signal: {s.get('signal')} | Combined Confidence: {s.get('confidence', 0)*100:.1f}%
ML: {s.get('ml_reasoning', '')[:300]}
Kronos: {s.get('kronos_reasoning', '')[:300]}
SLM: {s.get('slm_reasoning', '')[:300]}
Stop Loss: ₹{s.get('stop_loss', 0):.1f} | Target: ₹{s.get('target', 0):.1f}
"""

    prompt = f"""You are reviewing intraday NSE stock signals generated by ML + Kronos + SLM models.

{f"Recent learning from past sessions:{chr(10)}{learnings_context}{chr(10)}" if learnings_context else ""}

SIGNALS TO REVIEW:
{signal_block}

For each signal, provide:
1. CONFIRM or REJECT (with brief reason, 1 sentence max per signal)
2. Adjusted confidence (0.0-1.0)
3. Any additional insight the models may have missed

Respond as JSON array:
[{{"ticker": "X", "action": "CONFIRM|REJECT", "confidence": float, "note": "brief insight"}}]

Be concise and decisive. No lengthy explanations."""

    system = """You are a senior Indian stock market analyst reviewing algorithmic signals.
You have deep knowledge of NSE market microstructure, Nifty sector dynamics, FII behavior patterns,
and Indian corporate earnings cycles. You think fast and sharp. Under 2 minutes for this batch.

Execution reality check (StockSense is currently PAPER-only, but reason as if
real execution mechanics apply, since eventual live accuracy depends on it):
orders realistically fill as LIMIT, not MARKET, near the quoted price with
some slippage; round-trip costs (brokerage + STT + slippage) run roughly
0.25-0.35%. A signal whose edge is thinner than that after a stop/target
band isn't worth confirming even if the raw model confidence looks decent."""

    raw = _run_claude(prompt, CLAUDE_SONNET, system=system)

    if not raw:
        status = llm_cli.get_component_status()
        log.warning("Claude returned empty response for intraday check (%s)", status["detail"])
        for s in signals:
            s["synthesis_status"] = status
        return signals

    # Parse JSON from response
    claude_outputs = _extract_json(raw, expect="array")
    if isinstance(claude_outputs, list):
        claude_map = {c["ticker"]: c for c in claude_outputs if isinstance(c, dict) and "ticker" in c}

        enriched = []
        for s in signals:
            c = claude_map.get(s["ticker"], {})
            action = c.get("action", "CONFIRM")
            adj_conf = c.get("confidence", s.get("confidence", 0.5))
            note = c.get("note", "")

            s["claude_action"] = action
            s["claude_confidence"] = adj_conf
            s["claude_reasoning"] = (
                f"{llm_cli.active_label()} ({action}):\n"
                f"  • {note}\n"
                f"  • Final confidence: {adj_conf*100:.1f}%"
            )
            s["final_confidence"] = adj_conf
            if action == "REJECT":
                s["signal"] = "HOLD"
            enriched.append(s)
        return enriched

    log.warning(f"Could not parse Claude JSON array. Raw: {raw[:500]}")
    return signals


def eod_review_call(predictions: list[dict]) -> dict:
    """
    EOD Claude Opus call. Reviews all predictions vs actuals.
    Returns structured learnings.
    predictions: [{ticker, signal, predicted_close, actual_close, ml_reasoning, kronos_reasoning, slm_reasoning, claude_reasoning}]
    """
    if not predictions:
        return {"learnings": [], "summary": "No predictions today."}

    pred_block = ""
    for p in predictions:
        delta = ((p.get("actual_close", 0) - p.get("predicted_close", 0)) / p.get("predicted_close", 1)) * 100
        outcome = "✅ Correct" if (
            (p.get("signal") == "BUY" and delta > 0) or
            (p.get("signal") == "SELL" and delta < 0)
        ) else "❌ Wrong"
        pred_block += f"""
{outcome} | {p['ticker']} | Signal: {p.get('signal')}
  Predicted: ₹{p.get('predicted_close', 0):.1f} → Actual: ₹{p.get('actual_close', 0):.1f} ({delta:+.1f}%)
  ML said: {p.get('ml_reasoning', '')[:200]}
  Kronos said: {p.get('kronos_reasoning', '')[:200]}
  SLM said: {p.get('slm_reasoning', '')[:200]}
  Claude said: {p.get('claude_reasoning', '')[:200]}
"""

    prompt = f"""End-of-day model performance review for NSE trading signals.

TODAY'S PREDICTIONS VS ACTUALS:
{pred_block}

Analyze each wrong prediction deeply:
1. What did the models miss?
2. What pattern should be learned?
3. What market condition caused the failure?

Also note what worked well and why.

Provide structured learnings as JSON:
{{
  "summary": "one paragraph summary of today",
  "learnings": [
    {{
      "ticker": "X or null for general",
      "title": "short title",
      "body": "detailed learning",
      "tags": ["pattern_failure|signal_type|sector|timeframe"],
      "model_at_fault": "ml|kronos|slm|claude|all"
    }}
  ],
  "accuracy_today": {{
    "total": int,
    "correct": int,
    "pct": float
  }}
}}"""

    system = """You are a rigorous quantitative analyst doing post-market review.
You extract precise, actionable learnings from prediction errors.
Your job is to make this system smarter for tomorrow.
Be specific about what pattern failed, not generic platitudes."""

    raw = _run_claude(prompt, CLAUDE_SONNET, system=system)

    if not raw:
        status = llm_cli.get_component_status()
        return {
            "learnings": [], "summary": "Claude review failed — no response.",
            "synthesis_status": status,
        }

    parsed = _extract_json(raw, expect="object")
    if isinstance(parsed, dict):
        return parsed

    log.error(f"Failed to parse EOD review JSON. Raw: {raw[:500]}")
    return {"learnings": [], "summary": raw[:1000], "raw": raw}


def calibration_call(day_stats: dict, current_params: list[dict], learnings: list[dict]) -> dict:
    """
    Nightly self-calibration — Claude Opus proposes bounded adjustments to the
    brain's adaptive parameters based on the day's realized outcomes.
    current_params: [{param_name, value, min_value, max_value}]
    Returns {"changes": [{"param": str, "new_value": float, "reason": str}], "summary": str}.
    An empty/unparseable response means NO changes — fail-safe by design.
    """
    params_block = "\n".join(
        f"- {p['param_name']}: {p['value']} (allowed range {p['min_value']}–{p['max_value']})"
        for p in current_params
    )
    learnings_text = "\n".join(
        f"- {l.get('title')}: {(l.get('body') or '')[:200]}"
        for l in (learnings or [])[:20]
    ) or "(none today)"

    prompt = f"""Nightly calibration for the StockSense autonomous paper-trading brain.

TODAY'S OUTCOMES:
{json.dumps(day_stats, indent=2, default=str)}

CURRENT ADAPTIVE PARAMETERS (each clamped to its allowed range — you may only adjust these, nothing else):
{params_block}

TODAY'S LEARNINGS:
{learnings_text}

Decide whether any parameter should move, and by how much. Principles:
- Small steps: never move a parameter more than ~10% of its allowed range in one night.
- If win rate is poor or many auto-buys stopped out, consider raising confidence_threshold or lowering max_position_pct.
- If the brain passed on signals that would have won, consider the opposite — but only with evidence from the outcomes above.
- If there is not enough data to justify a change (e.g. <5 resolved trades), change NOTHING.

Respond as JSON only:
{{
  "summary": "one-paragraph rationale",
  "changes": [
    {{"param": "exact_param_name", "new_value": float, "reason": "specific evidence-based reason"}}
  ]
}}
An empty changes array is a perfectly good answer."""

    system = """You are the calibration controller of an autonomous trading system.
You are conservative: parameters move only on clear evidence, in small steps.
You may ONLY propose changes to the listed parameters within their stated ranges.
Respond with JSON only."""

    raw = _run_claude(prompt, CLAUDE_SONNET, system=system)
    if not raw:
        status = llm_cli.get_component_status()
        return {
            "changes": [], "summary": "Calibration call returned no response — no changes.",
            "synthesis_status": status,
        }

    parsed = _extract_json(raw, expect="object")
    if isinstance(parsed, dict) and isinstance(parsed.get("changes"), list):
        return parsed

    log.warning(f"Calibration JSON unparseable — no changes. Raw: {raw[:300]}")
    return {"changes": [], "summary": "Unparseable calibration response — no changes.", "raw": raw[:1000]}


def weekend_deep_review(week_learnings: list[dict], accuracy_stats: dict) -> dict:
    """
    Saturday morning — Claude Opus deep weekly analysis.
    """
    if not week_learnings:
        return {"insights": [], "recommendations": []}

    learnings_text = "\n".join(
        f"- [{l.get('learning_date')}] {l.get('title')}: {l.get('body', '')[:300]}"
        for l in week_learnings[:50]
    )

    prompt = f"""Weekly deep review of StockSense NSE trading system.

ACCURACY THIS WEEK:
{json.dumps(accuracy_stats, indent=2)}

LEARNINGS LOGGED THIS WEEK:
{learnings_text}

Provide:
1. Recurring failure patterns (what keeps going wrong?)
2. Strongest signal patterns (what's working consistently?)
3. Market regime assessment (trending/ranging/volatile?)
4. Specific model calibration recommendations
5. Sectors to watch or avoid next week

JSON response:
{{
  "regime": "trending|ranging|volatile|mixed",
  "recurring_failures": ["..."],
  "working_patterns": ["..."],
  "model_calibration": {{"lgbm": "...", "kronos": "...", "slm": "..."}},
  "next_week_focus": ["sector or pattern to prioritize"],
  "weekly_grade": "A|B|C|D"
}}"""

    raw = _run_claude(prompt, CLAUDE_SONNET)
    if not raw:
        return {"insights": [], "recommendations": []}

    parsed = _extract_json(raw, expect="object")
    if isinstance(parsed, dict):
        return parsed

    return {"raw_review": raw}
